config/routes.rb
Rails.application.routes.draw do
root 'users#new'

  get 'wines/show'
  get 'wines/new'
  get 'wines/destroy'

  get 'posts/:post_id/comments' => 'comments#index'
  post 'posts/:post_id/comments' => 'comments#create', as: :post_comments
  get 'posts/:post_id/comments/new' => 'comments#new'
  get 'posts/:post_id/comments/id/edit' => 'comments#edit'
  get 'posts/:post_id/comments/:id' => 'comments#show'
  patch 'posts/:post_id/comments' => 'comments#update'
  put 'posts/:post_id/comments' => 'comments#update'
  delete 'posts/:post_id/comments' => 'comments#destroy'

  get 'posts/new'
  get 'posts/:id' => 'posts#show', as: :post
  get 'posts' => 'posts#new'
  post 'posts' => 'posts#create'
  get 'posts/:id/edit' => 'posts#edit', as: :edit_post
  patch 'posts/:id' => 'posts#update'
  delete 'posts/:id' => 'posts#destroy'

  get 'users' => 'users#index'
  get 'users/new' => 'users#new'
  post 'users' => 'users#create'
  get 'users/welcome_user'
  get 'users/new_user_profile'

  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :wine
  has_many :comments
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts
  has_many :wines, :through => :posts
  validates :email, uniqueness: true
  validates :password, presence: true,
                    length: { minimum: 5 }
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  has_many :posts
  has_many :users, :through => :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :null_session

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
    @user = User.find(session[:user_id])
  end

  def new
    @user = User.find(session[:user_id])
    @post = Post.new({user_id: session[:user_id]})
  end

  def new_user_profile
    @user = User.find(session[:user_id])
    @posts = Post.all.order(created_at: 'ASC')
  end

  def edit
    @post = Post.find(params[:id])
  end

  #Create a new post
  def create
    @user = User.find(session[:user_id])
    @post = @user.posts.new(post_params)
    if @post.save
      redirect_to "/posts/#{@post.id}"
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

  redirect_to '/users'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :image, :rating, :user_id, :wine_id)
  end

  def comment_params
      params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      puts user.id
      session[:user_id] = user.id
      redirect_to "/users"
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = User.find(session[:user_id])

  end



  def welcome_user
    @users = User.all
    @user = User.find(session[:user_id])
  end

  def new_user_profile
    @users = User.all
    @user = User.find(session[:user_id])
    @posts = Post.all.order(created_at: 'DESC')
  end

  def new
    @user = User.new
  end

  #Create a new User
  def create
    @user = User.new({
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
      password_confirmation: params[:password_confirmation]
    })

    if @user.save
      session[:user_id] = @user.id
      redirect_to "/users/welcome_user"
    else
      flash[:notice] = "Must be a unique email address"
      flash[:notice] = "Password must be longer than 5 characters!"
      render :new

    end
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  def show
  end

  def new
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WyntasteApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.label :text, "Content" %>
  <%= f.text_field :text %>
  <%= f.label :image %>
  <%= f.file_field :image%>
  <%= f.submit %>
<% end %>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>

<%= render 'form' %>

<% end %>

app/views/posts/new.html.erb
<h1>Create New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @post.rating %>
</p>

<p>
  <%= image_tag @post.image.url(:large) %>
</p>

<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<h2>Comments</h2>
<% @post.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Log Out', logout_path, method: :delete %>
<%= link_to 'Profile', '/users' %>

app/views/users/index.html.erb
<h1>Good to see you again, <%= @user.first_name.titleize %></h1>

<% if @user.posts.count > 0 %>
  <p>Here is the last wine you drank:</p>

  <%= @user.posts.last.title %>
  <%= @user.posts.last.text %>
  <%= @user.posts.last.rating %>
  <%= image_tag @user.posts.last.image.url(:large) %>
<% else %>
  <p>You haven't had any wine yet. What are you waiting for?</p>
<% end %>
<br>

<%= link_to '<button>Create New Post</button>'.html_safe, posts_new_path %>

<table>
  <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan='3'></th>
    </tr>

  <% @user.posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td><%= post.rating %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
       <td><%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>

  <% end %>
</table>

<%= link_to 'Log Out', logout_path, method: :delete %>

app/views/users/new.html.erb
<h1>Wyn App</h1>

<form action="/users" method="post">
  <label>First Name</label>
  <input name="first_name" type="text" placeholder="First Name">
  <br>
  <br>
  <label>Last Name</label>
  <input name="last_name" type="text" placeholder="Last Name">
<br>
<br>
  <label>Email</label>
  <input name="email" type="email" placeholder="Email">
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
<br>
<br>
  <label>Password (min 5 characters)</label>
  <input name="password" type="password" placeholder="Password">
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
<br>
<br>
  <label>Password Confirmation</label>
  <input name="password_confirmation" type="password" placeholder="Password Confirmation">
<br>
<br>
  <button>Sign Up</button><%= link_to '<button>Login</button>'.html_safe, login_path %>
</form>

<!-- Render the flash message here ... or nearby
 -->
<br>
<br>
<br>
<br>
<br>
<br>
<p>This is a paragraph about the site and some basic info.  To be populated at a later date</p>

app/views/users/new_user_profile.html.erb
<h1>Welcome <%= current_user.first_name.titleize %></h1>

<%= link_to '<button>Create New Post</button>'.html_safe, posts_new_path %>

<h2>Current Users are busy drinking:</h2>

<table>
  <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan='3'></th>
    </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
    </tr>

  <% end %>
</table>

<%= link_to 'Log Out', logout_path, method: :delete %>

app/views/users/welcome_user.html.erb
<h1>Welcome <%= @user.first_name %></h1>

<p>Thanks for joining wyn app!  This is your number one
resource for tracking your wines and learning while you do so.</p>

<p>To get started, please add a picture of yourself, and then you can move onto
learning more about wine and creating your first post!</p>

<p>To upload your picture, please click <strong>here</strong>.</p>
<%= link_to '<button>Later</button>'.html_safe, '/users/new_user_profile' %>

<%= link_to 'Log Out', logout_path, method: :delete %>

app/views/wines/destroy.html.erb
<h1>Wines#destroy</h1>
<p>Find me in app/views/wines/destroy.html.erb</p>

app/views/wines/new.html.erb
<h1>Wines#new</h1>
<p>Find me in app/views/wines/new.html.erb</p>

app/views/wines/show.html.erb
<h1>Wines#show</h1>
<p>Find me in app/views/wines/show.html.erb</p>